uploads = []
outputs = []

[[generated]]
id = "4lKe9HOcj8WVuqxPBXui7"
uri = "file://artifacts/sweet-mama-farms/public/hero.png"
type = "image"
title = "Hero Nigerian farm produce"

[[generated]]
id = "wO9LZ0a3YtqDuaxgJmdJN"
uri = "file://artifacts/sweet-mama-farms/public/grains.png"
type = "image"
title = "Grains and cereals"

[[generated]]
id = "nAx2uqZrgaj2G7sLy9SnP"
uri = "file://artifacts/sweet-mama-farms/public/poultry.png"
type = "image"
title = "Poultry and eggs"

[[generated]]
id = "mmWlGdIOFmEDwvgJlIWBj"
uri = "file://artifacts/sweet-mama-farms/public/vegetables.png"
type = "image"
title = "Fresh vegetables"

[[generated]]
id = "n6RPEaHt2RtC4VawO4G25"
uri = "file://artifacts/sweet-mama-farms/public/processed.png"
type = "image"
title = "Processed packaged foods"

[[generated]]
id = "rMbMvXDTAOSH_f6i2cJLB"
uri = "file://artifacts/sweet-mama-farms/public/palm.png"
type = "image"
title = "Red palm oil"

[[generated]]
id = "Ub31wCdtG4S144GqJ2QxP"
uri = "file://artifacts/sweet-mama-farms/public/gallery-1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "B5-FGkFbYA9pjl9JCU1GS"
uri = "file://artifacts/sweet-mama-farms/public/gallery-2.png"
type = "image"
title = "generated_image"

[[generated]]
id = "P6Aea7vFsy8MCLgm8NVZU"
uri = "file://artifacts/sweet-mama-farms/public/gallery-3.png"
type = "image"
title = "generated_image"

[[generated]]
id = "DDb3JvgLt5xjp20icLt8p"
uri = "file://artifacts/sweet-mama-farms/public/gallery-4.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Ut1-h10c33WLlYwIRuDFY"
uri = "file://artifacts/sweet-mama-farms/public/gallery-5.png"
type = "image"
title = "generated_image"

[[generated]]
id = "pclbo73gcwmMPZWayEtfw"
uri = "file://artifacts/sweet-mama-farms/public/gallery-6.png"
type = "image"
title = "generated_image"
